### ISSUE TITLE
[BUG] Impossible to build from source, errors out every time I try.

### ISSUE THREAD

**Issue by GoldenFurredFox** [QuestCraftPlusPlus/PojavLauncher#17]
### Describe the bug

Trying to run gradlew.bat or do the command gradlew assemble returns an error.

### The log file and images/videos

https://gist.github.com/SoulNylium/0d98ba7bc9b6294e0335ed9ec832052b

### Steps To Reproduce

```markdown
Run gradlew assemble in Windows Powershell
Get error within the first few seconds
Assembling stops immediately
```

### Expected Behavior

Run gradlew assemble
Gradle takes the approximate 1.5 to 3 minutes to build
Jar files are exported to the build/libs folder(s)

### Platform

```markdown
- Device model: Acer Aspire E5-575 (Acer Aspire E15 2016)
- CPU architecture: Intel Core i5 6200U
- Android version: Haven't gotten that far
- PojavLauncher version: Haven't gotten that far
```

**Comment by ProtatoPlus** [comment]
Same here any ideas?

**Comment by thejudge156** [comment]
Build not assemble

**Comment by GoldenFurredFox** [comment]
> Build not assemble

I did build first, then assemble. Same issue.

**Comment by thejudge156** [comment]
Your JDK is not set to Java 17

**Comment by Exist43** [comment]
I can't sign in with Microsoft Account, it just brings up error ERR_Name_Not_Resolved on my quest... help

**Comment by Flamgop** [comment]
Follow the [pojav building guide](https://pojavlauncherteam.github.io/android/install-guide/building.html#building), then if that doesn't work tell us.

**Comment by Flamgop** [comment]
Closing unless issue re-appears after following proper build guide.
