### ISSUE TITLE
[BUG] Microsoft account login error

### ISSUE THREAD

**Issue by Exist43** [QuestCraftPlusPlus/PojavLauncher#18]
### Describe the bug

I can't sign in with microsoft account, when I login with Microsoft on pojav launcher on my quest, it says ERR_Name_Not_Resolved.... help....

### The log file and images/videos

s

### Steps To Reproduce

```markdown
s
```

### Expected Behavior

i expect the game to let me sign in

### Platform

```markdown
- Device model: Oculus quest 2
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by ATXLtheAxolotl** [comment]
https://github.com/QuestCraftPlusPlus/QuestCraft/issues/7

**Comment by MrNavaStar** [comment]
closed on main repo
