### ISSUE TITLE
[F-Req] <Build Instructions>

### ISSUE THREAD

**Issue by veneficium42** [QuestCraftPlusPlus/PojavLauncher#34]
### Describe the request.

The build section just says coming soon, but it's been a lot.
I would like to build from source to test the newest features and hopefully help bug reporting.

**Comment by MrNavaStar** [comment]
You can download the latest versions from the actions tab for now, they build with every commit

**Comment by veneficium42** [comment]
Is auto-install packed in the launcher actions??

**Comment by MrNavaStar** [comment]
Yes
